server:
  port: 8080

spring:
  application:
    name: viool

  datasource:
    url: jdbc:postgresql://localhost:5432/viool
    username: viool
    password: viool
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jooq:
    sql-dialect: POSTGRES

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
